name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: Check Installed CMake Versions
      run: ls -l /usr/local/lib/android/sdk/cmake/
    - run: |
        chmod +x ./gradlew
        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: zygisk-imgui-modmenu
        path: out/magisk_module_release/
